skins:
  - url: https://steamcommunity.com/market/listings/730/MP7%20%7C%20Army%20Recon%20%28Field-Tested%29
    float: # Leave empty for ANY
    price: 100
    pages: 2
    pattern: 502, 800
  - url: https://steamcommunity.com/market/listings/730/UMP-45%20%7C%20Urban%20DDPAT%20%28Factory%20New%29
    float: 
    price: 
    pages: 2
    pattern: 123